version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: "example"
      POSTGRES_USER: "example"

  pws-backend:
    depends_on:
      - db
    build: .
    ports:
      - 8080:8080
    environment:
      SERVER_PORT: 8080
      JDBC_DATABASE_URL: "jdbc:postgresql://db:5432/"
      JDBC_DATABASE_USERNAME: "example"
      JDBC_DATABASE_PASSWORD: "example"